### ISSUE TITLE
0.35.0 keeps asking for update

### ISSUE THREAD

**Issue by nagim** [sean-codes/atom-browser#1]
Hi,

The 0.35.0 release always asks for updating, somehow the version number displayed in atom is stuck on 0.9.0. It seems to update fine (and the package.json tells it's 0.35.0), after restart it asks to update again.
Tried uninstall and install again, same.
Not a big deal, but I thought I let you know.

Thanks!

**Comment by sean-codes** [comment]
Hi @nagim! We are on version 0.48.0 can you please try to update and see if we are still getting that same issue! Ty! :)

**Comment by nagim** [comment]
Hi @sean-codes! I uninstalled and reinstalled and problem solved with the new version. Thanks a lot!
