### ISSUE TITLE
RWD view in browser

### ISSUE THREAD

**Issue by mpieszczyk** [sean-codes/atom-browser#12]
Is it possible to add RWD view to browser?

**Comment by sean-codes** [comment]
@mpieszczyk Hi, I scanned through the <webview> documentation and I am not seeing a setting for that. Possibly that view is a chrome specific tool and not in chromium.

https://electronjs.org/docs/api/webview-tag

**Comment by mpieszczyk** [comment]
You can turn this function, when You run inspect tool (F12). Then on the left side, there are two buttons - rectangle with arrow, and near 2 rectangles looking like smartphone and tablet. To run RWD view need to click on second one.

**Comment by sean-codes** [comment]
@mpieszczyk yes, in google chrome that is where the button is in the devtools. In the chromium that atom is using that button does not seem to be available.
