### ISSUE TITLE
SSI not recognised

### ISSUE THREAD

**Issue by wrogner** [sean-codes/atom-browser#17]
This package is very usefull, thank you.

I found just one issue that you may want to consider fixing:

If the html page has a server side include directive that loads an integrated page, this statement is ignored instead of carried out.

here is an example

...
<body class="rsb-fade-in">

...

In this case it would be helpful, it the navigation bar and header banners would be loaded in the preview.

**Comment by sean-codes** [comment]
@wrogner Would you be able to provide steps to reproduce on my side?

**Comment by sean-codes** [comment]
Closing!
