### ISSUE TITLE
Transparent background instead of white

### ISSUE THREAD

**Issue by ecker00** [sean-codes/atom-browser#2]
To use this for web development and expecting similar results in a regular web browser, the default background should be white. At the moment it's transparent, matching your Atom theme.

I'm not sure if this is a feature or a bug. It's actually kinda neat, but then should be a toggleable option. Really liking this package! 👍

**Comment by sean-codes** [comment]
Ty for bringing this to attention! There is now a setting so we can turn the white background on or off! Please let me know if we need to do anything else for this!
