### ISSUE TITLE
atom-browser auto reload function to slow

### ISSUE THREAD

**Issue by therealokoro** [sean-codes/atom-browser#21]
Hello, i've noticed that when using the atom-browser package, the auto reload function works slowly.

Can this be put into consideration please. Thank You

**Comment by sean-codes** [comment]
@REDEAKAA ty for bringing this up! i will take a look!

**Comment by sean-codes** [comment]
Merged and published! https://github.com/sean-codes/atom-browser/pull/22

![update1 1 0](https://user-images.githubusercontent.com/21677355/63146194-beaa4780-bfbf-11e9-92a4-18acb3be86d6.gif)

**Comment by therealokoro** [comment]
Thanks for checking it out, i hope the update fixes the problem.
Love your work 😊😊
