### ISSUE TITLE
No touch simulation on click and drag

### ISSUE THREAD

**Issue by ghost** [sean-codes/atom-browser#23]
Really nice but .. do you have a touch simulation inside?? because I am trying to test the interface of the my app (web) and does not take the drag (obviously chrome firefox yes, it is certain that the system works).

thanks.

**Comment by sean-codes** [comment]
@ShapeGroup thanks for opening an issue! Would you mind providing an example I could test? I tried with the dragula front page and was able to drag and drop. 

![drag-and-drop-within-atom-browser](https://user-images.githubusercontent.com/21677355/67807885-a052d480-fa63-11e9-9b5a-181477a2ed86.gif)

**Comment by ghost** [comment]
Because the drag is based on mouse events and not collective. To test a cross-app, you need to enter debug mode (F12 (or Ctrl+shift+M directly for touch simulation in firefox) ) and click on the simulate touch .

Obviously I will try as soon as I can to provide.

In any case: you can test by trying ontouchstart or move, to understand that the event, apparently, is not taken in any way.

I will shortly provide code ;)

little rapid exemple:

mydiv.ontouchstart = event => { do... }
mydiv.ontouchmove = event => { do... }
mydiv.ontouchend = event => { do... }

or
mydiv.ontouchstart = dragStart;  // in cross-app
mydiv.onmousedown = dragStart; // web

mydiv.ontouchmove = dragMove; // in cross-app
mydiv.ondrag = dragMove; // web

mydiv.ontouchend = dragEnd; //  in cross-app
mydiv.onmouseup = dragEnd; // web

function dragStart(){ do... }
function dragMove(){ do... }
function dragEnd(){ do... }

**Comment by sean-codes** [comment]
@ShapeGroup Ah okay! I think this might have been brought up before in the past. `atom-browser` uses an electron webview and the events / devtools available are provided through there. 

The mobile button (deviceEmulation) that you might find in firefox/chrome seems is not available. :(
![Screen Shot 2019-11-11 at 8 54 15 AM](https://user-images.githubusercontent.com/21677355/68596612-1e9a7800-0461-11ea-8369-5f1ce28ad57d.png)

Additional information:
https://github.com/electron/electron/issues/5488
https://electronjs.org/docs/api/webview-tag
