### ISSUE TITLE
Default Location Bug?

### ISSUE THREAD

**Issue by Lunokes** [sean-codes/atom-browser#28]
Hey Sean,

Is there a known issue with the Default Location not working correctly? 

Every time I reopen Atom the dock location is at the bottom on any file I open, even if in settings it's set to Right Dock (and Right Dock is the default too, so even stranger?). Every time I open a file I'm going into the settings to manually change it again at the moment.

Thanks again!
Luke

**Comment by sean-codes** [comment]
@Lunokes This is entirely possible! Can you send me a screen shot of what your settings look like?  If you open console `cmd-option-i` we should also be able to type in `atom.config.get('atom-browser')` and see what kind of weirdness we are getting!

<img width="672" alt="Screen Shot 2019-11-17 at 1 09 42 PM" src="https://user-images.githubusercontent.com/21677355/69012492-21530c80-093c-11ea-841a-9e57842c15ea.png">

Can you also double check that there are not any floating atom-browser tabs in your window? We should only ever be able to have one atom-browser tab open and this could be interfering. 

Also by open a file I assume you mean right clicking the file and pressing `atom preview`?

**Comment by Lunokes** [comment]
@sean-codes Hey Sean, thanks for the reply.

Your comment about floating tabs got me wondering whether it was clashing with another package and it appears to be right. I have some Linters installed which are docked at the bottom by default, and it seems when your browser fires it just attaches to that in a new tab rather than firing up a new dock to the right. I disabled all the linters, restarted Atom and it's absolutely flawless now. Not sure if it's one you'd still want to look into fixing?

Luke

**Comment by sean-codes** [comment]
@Lunokes Ah, I'm going to install a linter and see if I can reproduce. Then we can find a way to fix this!

**Comment by Lunokes** [comment]
@sean-codes Seems to have been htmlhint that was the perpetrator!

**Comment by sean-codes** [comment]
@Lunokes I know this was quite awhile ago but I had a moment to figure out this bug. I had atom-browser listening to all dock changes and not checking to make sure the change was by us. Causing any other docked plugins to trigger setting atom-browsers dock location! Thanks a bunch for reporting this!

https://github.com/sean-codes/atom-browser/pull/29

**Comment by Lunokes** [comment]
@sean-codes Hey Sean, hope you had a good Christmas and New Year. Thanks a lot for taking a look at this! Really glad it's fixed, still using and loving the plugin.
