### ISSUE TITLE
Request : Ability to have the browser open as a tab, instead of being in the dock

### ISSUE THREAD

**Issue by demperor-music** [sean-codes/atom-browser#31]

**Comment by vBuresh** [comment]
The ability to open the browser in the dock is a great idea and a very elegant solution. I use the Atom browser almost daily. Depending on the tasks, I often change the location (bottom or right dock). It is very convenient and compact. I'm afraid in tabs such flexibility is unattainable. This can be easily verified using other packages.

**Comment by sean-codes** [comment]
@JaKaWa I appreciate you opening a request! I would like to keep this plugin in the dock. Closing this issue.
