### ISSUE TITLE
A small problem - the browser does not work

### ISSUE THREAD

**Issue by vBuresh** [sean-codes/atom-browser#38]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Debian GNU/Linux
**Thrown From**: [atom-browser](ssh://git@github.com/sean-codes/atom-browser) package 1.8.0

### Stack Trace

Uncaught TypeError: this.html.webview.getWebContents is not a function

```
At /home/w/.atom/packages/atom-browser/lib/atom-browser-view-browser.js:207

TypeError: this.html.webview.getWebContents is not a function
    at AtomBrowserViewBrowser.reload (/packages/atom-browser/lib/atom-browser-view-browser.js:207:29)
    at /packages/atom-browser/lib/atom-browser-view-browser.js:119:65)
```

### Commands

```
     -0:31.9.0 intentions:highlight (input.hidden-input)
     -0:30.9.0 terminus:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-browser 1.8.0 
atom-js-code-to-svg-to-preview 0.1.0 
busy-signal 2.0.1 
double-tag 1.7.0 
emmet 2.4.3 
ftp-remote-edit 0.18.0 
intentions 1.1.5 
language-hugo 0.5.1 
language-markdown 0.37.0 
language-svg 0.9.2 
linter 2.3.1 
linter-htmlhint 1.6.3 
linter-sass-lint 1.9.0 
linter-ui-default 1.8.1 
markdown-writer 2.11.10 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-selection 4.5.0 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
svgo 4.0.0 
terminus 4.0.4 
```

**Comment by vBuresh** [comment]
Hi!

Still same problem. Browser does not work
![2020-06-05 16-41-07](https://user-images.githubusercontent.com/20504132/83884223-40d14b80-a74d-11ea-98ed-fe0e60485ff7.jpg)
![2020-06-05 16-41-57](https://user-images.githubusercontent.com/20504132/83884232-4464d280-a74d-11ea-8053-b17fc82c5cc1.jpg)

**Comment by Anirog** [comment]
@vBuresh

❗ The latest Atom 1.47 updates electron to version 5. Electron 5 disables webview by default. There is an update coming to atom to enable webview. If you use atom-browser or other webview based plugins like markdown preview plus please stay on version 1.46: https://github.com/atom/atom/releases/tag/v1.46.0.

**Comment by vBuresh** [comment]
Thank.  Very useful app.  I often use it
