### ISSUE TITLE
Request : Add a text size manipulator.

### ISSUE THREAD

**Issue by blueedgetechno** [sean-codes/atom-browser#40]
Hi, It would be very helpful if there will be a pair of buttons for increasing and decreasing the text size of the page.

**Comment by sean-codes** [comment]
Hi! Thanks you for feature request! This will be in next update.

![atom-browser-zoom-bar](https://user-images.githubusercontent.com/21677355/89860458-1d6db700-db69-11ea-9dff-cfc4e3cef4ec.gif)
