### ISSUE TITLE
No option to turn off cache of atom browser

### ISSUE THREAD

**Issue by Phu1237** [sean-codes/atom-browser#43]
Hi! I found that even if i turn on auto reload (bolt icon) the cache still not reload. It still load the old CSS files. Can you add any option to not save cache?

**Comment by sean-codes** [comment]
@Phu1237 That's a good idea! It looks like webview has something to reload without cache we might be able to implement! https://www.electronjs.org/docs/api/webview-tag#webviewreloadignoringcache

In the mean time I know it's a bit inconvenient but you can open atom-browser dev tools -> network tab -> check Disable cache

![image](https://user-images.githubusercontent.com/21677355/89854514-b0065a00-db59-11ea-98a2-363927702a53.png)

**Comment by Phu1237** [comment]
@sean-codes Thank for your response. Your package help me very much!
