### ISSUE TITLE
static/fixed dev tools window

### ISSUE THREAD

**Issue by Winston6079** [sean-codes/atom-browser#46]
Hi. Would it be possible to have the option of having the dev tools window fixed in the atom browser instead of floating?

**Comment by sean-codes** [comment]
I wish! This is something I explored a bit and it is not possible other than being able to send text back to atom and displaying / rendering it ourselves manually :(

If we wanted to do this we could try and take an open source implementation of a JS console like codepen did but I find it's quite a bit of work to only get text errors

![image](https://user-images.githubusercontent.com/21677355/121078349-7664a680-c79e-11eb-909a-2b1be3f6d32d.png)
