### ISSUE TITLE
Add support for multiple instances.

### ISSUE THREAD

**Issue by OldGitCorn** [sean-codes/atom-browser#47]
As I understand it, this project is never planning to add support for multiple tabs. A shame, considering this is likely the best browser on atom currently, although I can understand the appeal of wanting to focus work on the single tab experience. I do think, though, that allowing multiple instances would help a bit. Most add-ons allow you to split, like below.
![image](https://user-images.githubusercontent.com/57857282/110198814-fc70fa00-7e09-11eb-8c57-ba98dc4f0c86.png)
Attempting to split Atom Browser does nothing, if it worked as expected, it would be fantastic!

**Comment by sean-codes** [comment]
Hi @OldGitCorn I'm going to close this card. I do not plan on adding multiple browsers or a split mode. The focus on this extension has always been a single browser preview that works reliably. Thank you for opening an issue.
