### ISSUE TITLE
Suggested : Vertical Side By Side Viewing

### ISSUE THREAD

**Issue by tridentic** [sean-codes/atom-browser#55]
There is no such way to **_dock_** the browser side by side vertically along with a file. Isn't It **Mandatory**?

**Comment by blueedgetechno** [comment]
There is no option view a file as such, not yet. This is in bucket list.

**Comment by sean-codes** [comment]
@arjOman This feature is not planned. Atom-browser was made to be a simple dock package. You can drag atom browser into the vertical dock: https://github.com/sean-codes/atom-browser/issues/53#issuecomment-864449457
