### ISSUE TITLE
Way to clear cache?

### ISSUE THREAD

**Issue by CordCodes** [sean-codes/atom-browser#6]
I am working on a project where this plugin is coming in handy. I am working with sounds, but this browser has cached the sound, so I cannot change it. Is there a way to clear the cache? I have restarted atom and reinstalled atom-browser but the cache seems to still exist. Thank you in advance! 

(PS I love ur insta account)

**Comment by sean-codes** [comment]
@CordCodes Hi! Can you try using `ALT-CMD-X` / `ALT-WINDOWSKEY-X`. That will bring up the devtools. In devtools switch to Network and inside there you can see Disable Cache. Check that Box! Please let me know if that works out for you!

**Comment by CordCodes** [comment]
Yes, I think that works fine for me. Sorry I didn't notice your reply and answer it early, And I just seen that you added me as a contributer, thanks! I will try to be useful as I am 12 and only learning 
😃
