### ISSUE TITLE
What do you think about a REAL TIME CODING Feature

### ISSUE THREAD

**Issue by Sanix-Darker** [sean-codes/atom-browser#9]
it could be nice to have an instant preview of the code on atom browser while coding(Like code pen), is just an idea! That's a realy good project @sean-codes !

**Comment by sean-codes** [comment]
@Sanix-Darker This is not on my radar. I would look into adding that into your build tool like webpack/gulp autoreload. To much to maintain, would require configuration, doesn't work right out of the box, not simple etc.
